### PR TITLE
[PAXWEB-803] Updating or uninstalling WAB bundle doesn't free classes. Fixes for 3.1.X

### PR DESCRIPTION
**Pull request by rsmogura**
Those are simple fixes for 3.1.X;
- servlets hasn't been removed because servlet's model doesn't contain servlet class
- other small fixes
I'll add this to 4.X branches

### CODE REVIEW

**Comment by ANierbeck** [comment]
Hmm, 
sorry can't pull that one. 
This is due to two different reasons. 
1) The Commits are mixed, so it's not clear which one does actually change something belonging to issue PAXWEB-803 
2) The Picked Commit I did for PAXWEB-770, is by intention neither in the 4.x nor in the 3.x branch. It is an API Breaking change therefore to be correct by semantic versioning means can't be ported to 3.x or 4.x

Again, thanks for spotting and providing Patches I really appreciate this, and don't want to look like a Jackass, but due to the two reasons above I can not accept this :)

regards, Achim

**Comment by rsmogura** [comment]
No, you are not Jackass, you just try to keep this working!

If you will have time we can discuss few others possible bugs I spotted, but this time for master release.

**Comment by ANierbeck** [comment]
yeah, please file as much bugs as you might spot :-)
Some may have a deeper reason, remember the Servlet Instantiation through classes instead of class instances :-)

**Comment by rsmogura** [comment]
Can you give me an example (URL) of installation via classes?

**Comment by ANierbeck** [comment]
Hi,

sorry took me bit longer :)
All of the WAB or WAR samples should work that way already.
Might also want to take a look at a PaxCDI war sample.
For example at [1].

regards, Achim

[1] -
https://github.com/ANierbeck/karaf-enterprise-sample/tree/master/sample-view



2015-03-22 19:55 GMT+01:00 Radek <notifications@github.com>:

> Can you give me an example (URL) of installation via classes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.web/pull/27#issuecomment-84674400>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Pull request closed without merging**
