### PR TITLE
[PAXWEB-954] Disable Classpath scanning for ContainerInitializers for servlet version < 3

### PR DESCRIPTION
**Pull request by lostiniceland**
- Moved scanning-logik
- Bundle-Classloader adapted by BundleWiring
- Fix accompanied with test using tinybundles instead dedicated sample-project.
- Fixed minor warnings

### CODE REVIEW

**Comment by lostiniceland** [comment]
Please have a look at WebAppParser line 342. 

I had to change the classloader to make the tests work and according to my understanding it actually should have never worked the way it was before `bundle.getClass().getClassloader()`  yields the Classloader from the framework bundle, but the scanning must take place in the webapp-bundle.

**Comment by ANierbeck** [comment]
I'm not sure that it shouldn't have worked before (as it did ;) ) The bundle.getClass().getClassloader() isn't the framework one, but the web-application one. Depending on which the bundle actually is.

**Comment by ANierbeck** [comment]
I'm not sure that it shouldn't have worked before (as it did ;) ) The bundle.getClass().getClassloader() isn't the framework one, but the web-application one. Depending on which the bundle actually is.

**Comment by ANierbeck** [comment]
but looks ok to me ... feel free to merge.

**Comment by lostiniceland** [comment]
According to the spec (refering R6 10.4.7.6) the adaptation to BundleWiring should be the correct approach. 

> Returns the class loader for this bundle wiring. Since a bundle refresh creates a new bundle wiring
for a bundle, different bundle wirings for the same bundle will have different class loaders.

Going to cleanup the comments and merge this PR later today.

**Pull request merged**
