### PR TITLE
Refactored properties for ssl keystore password and ssl private key password.

### PR DESCRIPTION
**Pull request by damiri-ts**
See https://ops4j1.jira.com/browse/PAXWEB-927

### CODE REVIEW

**Comment by ANierbeck** [comment]
Looks good to me, feel free to merge any time. 
But only on the master branch. Due to API Breaking changes

**Comment by damiri-ts** [comment]
@ANierbeck can you clarify which changes specifically are API breaking? Maybe I can tweak things so that there are no API breaking changes. I did write the code so that it is backward compatible with the old property settings. I was hoping to merge this with the 3.2 branch so if there are any changes I can make so that it is compatible with that branch please let me know.

**Comment by ANierbeck** [comment]
It's more a behavioral change, but I've just seen that it's possible to use both parameters. 
So go ahead.

**Comment by damiri-ts** [comment]
@ANierbeck I added the old properties back into the metatype.xml just to make clear to the end user that they can still use them for backward-compatibility. I also added a note in the metatype names to explain that they are deprecated. Hopefully, this makes the changes a bit more clear to the end user. If there is existing documentation that you would like me to update I'd be happy to do that as well.

**Comment by ANierbeck** [comment]
Great, thank you.
We have doc in confluence and in the pax-web-manual sub module. But only
for 4 and 6.

sent from mobile device
Am 19.12.2015 2:05 vorm. schrieb "damiri-ts" <notifications@github.com>:

**Comment by damiri-ts** [comment]
@ANierbeck It looks like tests are consistently failing with:
```Exception in thread "ThreadedStreamConsumer" java.lang.OutOfMemoryError: Java heap space```
Has this ever happened before? Is there a way to bump up the Java heap memory for the CI?

**Comment by ANierbeck** [comment]
Hi, 

in this case might as well ignore these failures of travis and cirlceci, unfortunately the build for pax-web is just to much for those infrastructures to handle. http://ci.ops4j.org/jenkins is the build-server I rely on :-)

regards, Achim

**Comment by damiri-ts** [comment]
@ANierbeck Is there a way for me to trigger a build on that system for this pull request?

**Comment by ANierbeck** [comment]
unfortunately not


2015-12-19 21:06 GMT+01:00 damiri-ts <notifications@github.com>:

> @ANierbeck <https://github.com/ANierbeck> Is there a way for me to
> trigger a build on that system for this pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.web/pull/41#issuecomment-166020815>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by damiri-ts** [comment]
@ANierbeck OK. Well if it is OK with you, I will go ahead and merge. The integration tests pass fine on my machine and the CI passed for the 3.2.x version of these changes. I just want to make sure that I have your approval before I proceed.

**Comment by ANierbeck** [comment]
go ahead

**Pull request merged**
