### PR TITLE
PAXWEB-874 Changed bundle.getEntry to bundle.findEntries

### PR DESCRIPTION
**Pull request by WouterBanckenACA**
Fixed PAXWEB-874

### CODE REVIEW

**Comment by tomdw** [comment]
Can someone with write access make sure this gets merged and released? We have the same problem that we cannot correctly extend bundles which are composed from fragments and where 1 of the fragments contains the WEB.xml. According to the OSGi specs this should be made possible as the combination of the host bundle and fragment bundles should be considered as 1 bundle with the complete content.

**Comment by tomdw** [comment]
@ANierbeck in which release can we expect this pull request to be released?

**Comment by ANierbeck** [comment]
will be version 4.2.0 and 6.0.0

2015-08-10 20:29 GMT+02:00 tomdw <notifications@github.com>:

> @ANierbeck <https://github.com/ANierbeck> in which release can we expect
> this pull request to be released?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.web/pull/28#issuecomment-129558006>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by tomdw** [comment]
Ok, 4.2.0 would be great. When is it planned?

**Pull request merged**
