### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by orpiske**
These are all minor cleanups that should not affect the code logic anyhow.

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by orpiske** [comment]
@jbonofre I was looking into the failures. They don't seem to be caused by the PR. Looking at the history on Travis CI, it seems the builds are failing for a long time. So, I took some time and sent a PR that fixes the Travis builds. To summarize: the problems w/ the Travis CI build were primarily related to the maximum duration accepted by Travis CI builds. Even using the travis_wait trick to adjust how Travis CI checks for stale builds is insufficient because the total combined time for the build far exceeds the maximum amount of time allowed by Travis. 
I sent PR #231 as a proposal to fix this. 

Likewise, the problems on Circle CI seem unrelated to the changes on the PR, but I will take a look at it nonetheless. Should the solution be accepted, I will try to do the same kind of fix for Circle CI.

**Comment by jbonofre** [comment]
@orpiske agree with you. `master` is also failing on tomcat itest on my box. So, I have to fix this one as well.

**Comment by grgrzybek** [comment]
I cherry-picked the changes to `master` branch [as well](https://github.com/ops4j/org.ops4j.pax.web/compare/e03bb0549c5dd7ca9322a58717924c8232576b6c%5E...ab443ccacfa17203dfd1c6c2b67df9bc2f74b8f0).
Thanks @orpiske !

**Pull request merged**
