### PR TITLE
 [7.2.x] PAXWEB-1180 Add ability to specify a default authMethod and realmName for Jetty Container

### PR DESCRIPTION
**Pull request by KalCramer**
Creating 7.2.x PR based on comments: https://groups.google.com/forum/#!topic/ops4j/4XkeOKL7L6k

### CODE REVIEW

**Comment by KalCramer** [comment]
Seems like a timing issue that may have been addressed in master. How do I kick off another CI build? build now ?

**Comment by grgrzybek** [comment]
@KalCramer Please go ahead - I'm not sure how to do it ;)

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
OK, started https://circleci.com/gh/ops4j/org.ops4j.pax.web/855

**Comment by KalCramer** [comment]
@grgrzybek It'll all good on that run, disappointed it doesn't update that here on PR 😞

**Comment by grgrzybek** [comment]
Yeah - I'm not github - circleci integration expert. I'll merge this PR, but please give me a bit of time - I want to check something locally - tomorrow morning CET, ok?

**Comment by stsiano** [comment]
I am also no circleci expert, but  the tomcat integration tests keep failing with a timeout (that's why you don't get a proper error message). This was also the case for the additional build Grzegorz started.

This timeout is configured in .circleci/config.yml

Is it possible to update the update the pull request by changing line 123 in .circleci/config.yml from
 "no_output_timeout: 30m" to "no_output_timeout: 45m" ?

There are now three possibilities: 
The tomcat tests work with that change -> this means they just take longer than before.
The tomcat tests still fail with a timeout again -> this probably means that the change causes the tomcat tests to hang for some reason
The tomcat tests fail, but with a test error instead of the timeout -> in that case there is also something broken with tomcat, but we will get at least an error message

**Comment by grgrzybek** [comment]
I'll be checking this branch today.

**Comment by grgrzybek** [comment]
Tomcat tests simply hung for me at `org.ops4j.pax.web.itest.tomcat.WarJsfResourcehandlerIntegrationTest`...

**Comment by grgrzybek** [comment]
All tests passed - on my machine, I had to restart (`mvn -rf`) from pax-web-itest-container-tomcat, but even with only Tomcat, Undertow and Karaf tests it took 39 minutes...

**Comment by grgrzybek** [comment]
@KalCramer I allowed myself to clean some formatting issues.
Soon (next week?) I'll do pax-web 7.2.4 release.

**Comment by KalCramer** [comment]
@grgrzybek I just wanted to see if there was any update on the 7.2.4 release? Thank you!

**Comment by grgrzybek** [comment]
@KalCramer I have one more issue to fix in 7.2.x related to session management, but I didn't have time to finish it last week (at least I've started) - but I should have much more time in the incoming week.

**Comment by grgrzybek** [comment]
@jbonofre I'll do it - one more thing to merge

**Pull request merged**
