### PR TITLE
[PAXWEB-984] Improve Integration-Tests

### PR DESCRIPTION
**Pull request by lostiniceland**
Tests moved to new Test-API

Test-API enhancements
- Async
- Request-Timeout
- Post-Requests
- Cookie-Handling between Requests (keep Session alive, which is necessary for JSF-ViewState)
- Response-Body logged under INFO for easier debugging

WaitCondition enhanced
- configure duration and sleep
- specify Runnable as Lambda for custom timeout-handling
- WaitCondition2 as replacement for anonymous inner classes

Other improvements
- Fixed wrong antrun-configuration (test-container-poms) which was not executed
- Documentation
- Optimzed Imports

**Current Test-State**
Some test seem unreliable

- For example the Undertow-tests in class WarBasicAuthSecuredIntegrationTest are only failing in the first run. When retried they pass.
- Furthermore the custom error-pages, which are configured in fragments, are not served. The server sends a 403 but with its own page and not the error-page configured in the fragment
- A multipart-upload test is still ignored, because it seems Jetty HttpClient does not yet support it.

### CODE REVIEW

**Comment by ANierbeck** [comment]
I'm a bit irritated, the jenkins pull request build failed with 19 failed tests, will build locally.

**Comment by lostiniceland** [comment]
Yes, I know. I was hoping that you could give me some hints what might be wrong. I am working on those last test-failures for the last three days and I am getting a bit blind now.

I will continue working on this fork-branch and merge once everything is resolved. I currently just need some reviewer-help.

For instance, locally Undertow only fails with 3 tests whereas Jenkins fails with 9. Some tests fail in my IDE the first run, but pass in the second (which is also weird because the new test-client is stateless -> each call on executeTest gets a fresh instance). 

Anyhow, debugging should be easier now, because the new test-client also logs the response-body in case of content-type = text*

**Comment by ANierbeck** [comment]
locally it fails for 71 of the 187 tests of the jetty tests with:
Stream handler unavailable due to: null

**Comment by lostiniceland** [comment]
Thats weird. Did you clean everything? Locally Jetty fails with something around 12 or 14 of the Jetty-iTests for me.

**Comment by ANierbeck** [comment]
Regarding helping, fine with me, could you merge it in an extra branch then?
makes it easier to collaborate :)

**Comment by ANierbeck** [comment]
regarding the failing test, yep mvn clean install ...

**Comment by lostiniceland** [comment]
Closed as collaboration via feature-branch is easier. New branch improve-integration-tests pushed and Jenkins-Job for Feature-Branch reconfigured

**Pull request closed without merging**
