### PR TITLE
PAXWEB-1024 Register ServletContext as OSGi-service in all containers

### PR DESCRIPTION
**Pull request by lostiniceland**
Please review.

Synchronisation is handled by calling methods as far as I saw.

### CODE REVIEW

**Comment by ANierbeck** [comment]
looks good to me, but maybe @gnodet should also take a look.

**Comment by lostiniceland** [comment]
There is still at least one challenge with the current Undertow implementation regarding PAXWEB-906: A handler (and related stuff like deployment and a manager) is created once the server is started (which happens with the first registration, e.g. Servlet) but this handler is destroyed/undeployed if something changes. The handler is recreated with an incoming request.

This design can give us some headache with the HttpServiceRuntime (Whiteboard) because we are not able to get hold to a ServletContext until the first request was actually made!

It makes totaly sense to create the handler from scratch with all information after something changed. Was there a reason not to recreate the handler after the changes instead of waiting for the first request?
This reflects in the integration-tests: a initial request is not necessary for Tomcat, nor Jetty, but in Undertow.

**Comment by lostiniceland** [comment]
Since there are no objections I would like to merge this PR in order to continue on PAXWEB-906.

**Comment by ANierbeck** [comment]
yeah feel free to go :)

**Pull request merged**
