### PR TITLE
[PAXWEB-1007] Jetty Rewrite Handler cannot be used in jetty.xml

### PR DESCRIPTION
**Pull request by tadayosi**
UPDATED: https://ops4j1.jira.com/browse/PAXWEB-1007

### CODE REVIEW

**Comment by ANierbeck** [comment]
Thanks for the pull request ... usually we need a jira issue linked to this. 
So could you please open an issue for it, or give me the email adress to invite you to our issue tracker (unfortunate to do it this way, but due to spamming we needed to close down the self-registration :( )
Thanks, Achim

**Comment by tadayosi** [comment]
@ANierbeck Thanks. I already have the account for the JIRA so I'll open an issue soon :-)

This is really a maintenance pull req for a very old pax-web branch 1.1.x, so I just thought opening a n issue for it was too much. I was a bit too lazy...

**Comment by ANierbeck** [comment]
ha ... didn't see the 1.1.x version :)
thanks a lot anyways

**Comment by tadayosi** [comment]
Thanks @ANierbeck !

**Pull request merged**
