### PR TITLE
PAXWEB-875 Fixed package import

### PR DESCRIPTION
**Pull request by WouterBanckenACA**
Fixed PAXWEB-875

### CODE REVIEW

**Comment by tomdw** [comment]
Can someone with write access make sure this gets merged and released? We have the same problem.

**Comment by ANierbeck** [comment]
Hi,

I'm currently on the road.
Will take care of it next week.

Regards, Achim

sent from mobile device
Am 06.08.2015 4:09 nachm. schrieb "tomdw" <notifications@github.com>:

**Comment by tomdw** [comment]
@ANierbeck in which release can we expect this pull request to be released? When will it be planned to become available in the maven repositories?

**Comment by ANierbeck** [comment]
will be 4.2.0 and 6.0.0

2015-08-10 20:30 GMT+02:00 tomdw <notifications@github.com>:

> @ANierbeck <https://github.com/ANierbeck> in which release can we expect
> this pull request to be released? When will it be planned to become
> available in the maven repositories?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.web/pull/29#issuecomment-129558226>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by tomdw** [comment]
Ok, 4.2.0 would be great. When is it planned?

**Pull request merged**
